### PR TITLE
Support for v2.7.0.1

### PR DESCRIPTION
**Pull request by wenkokke**

### CODE REVIEW

**Comment by ruifengx** [comment]
Thanks for your work! It seems this change is not released in the `v2` tag, so it is currently only available in `setup-agda@master`. Is it an oversight?

**Comment by wenkokke** [comment]
Probably, yes. Maintaining the v2 tag is a pretty big effort, and I occasionally forget. I recommend you use the latest tag.

**Comment by ruifengx** [comment]
Okay, thanks! Somehow I missed the `latest` tag.

**Comment by ruifengx** [comment]
I just realised that the `latest` tag is also behind the `main` branch by this commit introducing support for Agda 2.7.0.1. I will use `setup-agda@main` for now.

**Comment by andreasabel** [comment]
I bumped `latest` and `v2` to the latest `main`.

**Comment by wenkokke** [comment]
> I bumped `latest` and `v2` to the latest `main`.

Thank you!

**Pull request merged**
